version: '3.8'

services:
  app:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Map port 3000 of the host to port 3000 in the container
    environment:
      - ENVIRONMENT=staging
      - MONGODB_URI=mongodb://localhost:27017/nervesx-bot
      - DISCORD_BOT_TOKEN=dummy
      - GUILD_ID=dummy
    restart: unless-stopped
